name: Build Android APK

on:
  push:
    branches: [ "main" ]   # Runs on push to main branch
  workflow_dispatch:        # Lets you run manually

jobs:
  build:
  - name: Set up Gradle
  uses: gradle/gradle-build-action@v2
   - name: Build debug APK
  run: gradle assembleDebug --no-daemon

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build debug APK
        run: ./gradlew assembleDebug --no-daemon

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: MyQRCard-APK
          path: app/build/outputs/apk/debug/app-debug.apk
          retention-days: 7
